### ISSUE TITLE
[Bug] [Meta] /UI/ can't handle a nested array parameter in the swagger spec

### ISSUE THREAD

**Issue by DaneelTrevize** [ccpgames/esi-issues#908]
# Bug

https://esi.evetech.net/ui/#/Routes/get_route_origin_destination

While investigating #907, it was discovered that the UI doesn't seem to support producing nested arrays, let alone an array of pairs, for the connections parameter of the route endpoint.

Inputting destination: `30000142`, origin: `30002187`, and then attempting to build a connections pairing of: `30003522,30000144` will result in the UI adding a strange somewhat-associated pair of text fields and "Add Item" & "-" buttons, but any single or comma/space separated values cannot be successfully used and instead result in `400: Bad Request` responses.

### Status Code

`400`

### Body

For space-separated single field use:  
```{
  "error": "failed to coerce value '[30003522' into type integer (format: int32), failed to coerce value '30000144]' into type integer (format: int32)"
}```

For comma-separated single field use:  
```{
  "error": "too few items for '.connections'"
}```

# Checklist

Check all boxes that apply to this issue:

- [x] Bug description is provided
- [ ] Request path is provided
- [x] Response status code is provided
- [ ] Response headers are provided
- [x] Response body is provided
- [ ] Expected response is provided

**Comment by a-tal** [comment]
https://github.com/ccpgames/esi-swagger-ui/issues/13

**Comment by a-tal** [comment]
oops, wrong one.

this is bad qs formatting though, https://esi.evetech.net/latest/route/30002187/30000142/?connections=30003522%7C30000144&datasource=tranquility&flag=shortest

**Comment by DaneelTrevize** [comment]
Any chance the endpoint description could be updated to link to that issue, so that devs see such a thing on /ui/ while it's not yet fixed? Or too nasty of a hack?
